using System.Text;
using Lore.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Lore.Services;

// Exports a generated daily horoscope as a PDF or as plain text. Both write the reading
// exactly as it was composed (sections, then the full list of transits behind it), so
// what is saved is what was on screen. Returns bytes; the caller writes the file.
public static class DailyExportService
{
    static DailyExportService()
    {
        // QuestPDF Community licence (free for individuals / <$1M revenue).
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public static byte[] ToPdf(DailyReading reading)
    {
        var doc = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(11)
                    .FontFamily("Segoe UI", "Segoe UI Symbol", "Segoe UI Historic"));

                page.Header().Column(col =>
                {
                    col.Item().Text($"{reading.Name} — Daily horoscope").FontSize(22).SemiBold();
                    col.Item().Text(reading.DateText).FontSize(11).FontColor(Colors.Grey.Darken2);
                });

                page.Content().PaddingVertical(12).Column(col =>
                {
                    col.Spacing(6);
                    col.Item().Text($"The day reads as {reading.Tone.Label()}")
                        .FontSize(12).SemiBold().FontColor(reading.Tone.ColorHex());

                    foreach (var section in reading.Sections)
                    {
                        col.Item().PaddingTop(8).Text(section.Heading).FontSize(15).SemiBold();
                        foreach (var item in section.Items)
                        {
                            col.Item().PaddingTop(2).Column(entry =>
                            {
                                if (item.HasTitle)
                                    entry.Item().Text(item.Title!).FontSize(11.5f).SemiBold();
                                if (item.HasMeta)
                                    entry.Item().Text(item.Meta!).FontSize(9).FontColor(Colors.Grey.Darken1);
                                entry.Item().Text(item.Text).FontSize(11).LineHeight(1.35f);
                            });
                        }
                    }

                    col.Item().PaddingTop(10).Text("All transits in effect").FontSize(13).SemiBold();
                    foreach (var line in reading.Trace)
                        col.Item().Text(line).FontSize(8.5f).FontColor(Colors.Grey.Darken2);
                    col.Item().PaddingTop(6).Text(
                        "Generated from the day's transits to this chart — a prompt for reflection, not a prediction.")
                        .FontSize(9).Italic().FontColor(Colors.Grey.Darken1);
                });

                page.Footer().AlignCenter().Text(x =>
                {
                    x.Span("Generated by Lore · ").FontSize(9).FontColor(Colors.Grey.Medium);
                    x.Span(DateTime.Now.ToString("yyyy-MM-dd")).FontSize(9).FontColor(Colors.Grey.Medium);
                });
            });
        });

        return doc.GeneratePdf();
    }

    public static byte[] ToText(DailyReading reading)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"{reading.Name} — Daily horoscope");
        sb.AppendLine(reading.DateText);
        sb.AppendLine($"The day reads as {reading.Tone.Label()}");

        foreach (var section in reading.Sections)
        {
            sb.AppendLine();
            sb.AppendLine(section.Heading.ToUpperInvariant());
            foreach (var item in section.Items)
            {
                sb.AppendLine();
                if (item.HasTitle) sb.AppendLine(item.Title);
                if (item.HasMeta) sb.AppendLine($"({item.Meta})");
                sb.AppendLine(item.Text);
            }
        }

        sb.AppendLine();
        sb.AppendLine("ALL TRANSITS IN EFFECT");
        foreach (var line in reading.Trace)
            sb.AppendLine(line);
        sb.AppendLine();
        sb.AppendLine($"Generated by Lore on {DateTime.Now:yyyy-MM-dd} — a prompt for reflection, not a prediction.");

        // UTF-8 with a byte-order mark, so Notepad and friends show the glyphs correctly.
        return [.. Encoding.UTF8.GetPreamble(), .. Encoding.UTF8.GetBytes(sb.ToString())];
    }
}
