using Lore.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Lore.Services;

// Exports a generated synastry reading as a PDF: the bi-wheel, the reading exactly as it
// was composed, then the full list of contacts behind it. Returns bytes; the caller
// writes the file.
public static class SynastryExportService
{
    static SynastryExportService()
    {
        // QuestPDF Community licence (free for individuals / <$1M revenue).
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public static byte[] ToPdf(Synastry synastry, SynastryReading reading, byte[] wheelPng)
    {
        var doc = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(11)
                    .FontFamily("Segoe UI", "Segoe UI Symbol", "Segoe UI Historic"));

                page.Header().Column(col =>
                {
                    col.Item().Text($"{reading.Title} — Synastry").FontSize(22).SemiBold();
                    col.Item().Text(BirthLine(synastry.First)).FontSize(10).FontColor(Colors.Grey.Darken2);
                    col.Item().Text(BirthLine(synastry.Second)).FontSize(10).FontColor(Colors.Grey.Darken2);
                });

                page.Content().PaddingVertical(12).Column(col =>
                {
                    col.Spacing(6);

                    if (wheelPng is { Length: > 0 })
                        col.Item().AlignCenter().Width(340).Image(wheelPng);

                    col.Item().Text($"The connection reads as {reading.Tone.Label()}")
                        .FontSize(12).SemiBold().FontColor(reading.Tone.ColorHex());

                    foreach (var section in reading.Sections)
                    {
                        col.Item().PaddingTop(8).Text(section.Heading).FontSize(15).SemiBold();
                        foreach (var item in section.Items)
                        {
                            col.Item().PaddingTop(2).Column(entry =>
                            {
                                if (item.HasTitle)
                                    entry.Item().Text(item.Title!).FontSize(11.5f).SemiBold();
                                if (item.HasMeta)
                                    entry.Item().Text(item.Meta!).FontSize(9).FontColor(Colors.Grey.Darken1);
                                entry.Item().Text(item.Text).FontSize(11).LineHeight(1.35f);
                            });
                        }
                    }

                    col.Item().PaddingTop(10).Text("All contacts between the two charts").FontSize(13).SemiBold();
                    foreach (var line in reading.Trace)
                        col.Item().Text(line).FontSize(8.5f).FontColor(Colors.Grey.Darken2);
                    col.Item().PaddingTop(6).Text(
                        "Generated from the contacts between the two birth charts — a prompt for reflection, not a verdict.")
                        .FontSize(9).Italic().FontColor(Colors.Grey.Darken1);
                });

                page.Footer().AlignCenter().Text(x =>
                {
                    x.Span("Generated by Lore · ").FontSize(9).FontColor(Colors.Grey.Medium);
                    x.Span(DateTime.Now.ToString("yyyy-MM-dd")).FontSize(9).FontColor(Colors.Grey.Medium);
                });
            });
        });

        return doc.GeneratePdf();
    }

    private static string BirthLine(NatalChart chart)
    {
        var c = chart.Celebrity;
        return $"{c.Name}:  {c.BirthDate}  ·  {c.BirthPlace}" +
               (c.BirthTimeKnown ? $"  ·  {c.BirthTime}" : "  ·  time unknown");
    }
}
